### ISSUE TITLE
Not an issue but a query regarding battery threshold

### ISSUE THREAD

**Issue by maniacx** [teackot/msi-ec#1]
Hey teackot.
Not raising an issue
I was interested in adding msi laptop to my extension **[Battery Health Charging](https://extensions.gnome.org/extension/5724/battery-health-charging/)**.
But I see two thresholds controls in sysfs and not sure how it works.
`/sys/class/power_supply/<supply_name>/charge_control_end_threshold`
`/sys/class/power_supply/<supply_name>/charge_control_start_threshold`
and
`/sys/devices/platform/msi-ec/battery_mode`
From what I have read battery mode (with predefined threshold) can be set to max, medium, min

But also can be set threshold charge_control_start_threshold and charge_control_end_threshold

My questions are
Can I set charging threshold to a custom value for example
`echo 74 | sudo tee  /sys/class/power_supply/<supply_name>/charge_control_end_threshold`
`echo 68 | sudo tee  /sys/class/power_supply/<supply_name>/charge_control_start_threshold`
Also can I read them with cat once they are set
`cat /sys/class/power_supply/<supply_name>/charge_control_end_threshold`
`cat /sys/class/power_supply/<supply_name>/charge_control_start_threshold`

And secondly what is the <supply_name> assigned?
Is it BAT0 or BAT-0 or something else? And is it the same for all models of msi supported in msi-ec?

**Comment by teackot** [comment]
Hi, @maniacx 

Really sorry for not answering, I had notifications disabled for this repo

`/sys/class/power_supply/<supply_name>/charge_control_<start/end>_threshold` are standard sysfs paths for battery thresholds.

You can set them to any values. `battery_mode` is just an entry for presets from official MSI Center: min is 50..60, medium is 70..80 and max is 90..100. I don't think I'll be adding `battery_mode` in the upstream kernel driver, since it just duplicates the standard sysfs entries.

> Can I set charging threshold to a custom value for example

Like I said, yes. The only restriction is that the values **are always 10% apart**, it's a hardware limitation.

> Also can I read them with cat once they are set

Yes

> And secondly what is the <supply_name> assigned?
> Is it BAT0 or BAT-0 or something else? And is it the same for all models of msi supported in msi-ec?

On my laptop it is BAT1. I'm not sure if it is the same on other models.

**Comment by teackot** [comment]
What you can do is check the `/sys/class/power_supply/` directory and use the `<supply_name>` that is present. Like I said, it's a standard sysfs entry, so it will also support all the other laptops that export battery thresholds there.

**Comment by maniacx** [comment]
Thank you for the reply. 
I was reading the msc-ec.c and it seems like it is not neccessary to apply both settings **charge_control_end_threshold** and **charge_control_start_threshold**.
For example, if I echo 70 > **charge_control_end_threshold** , the **charge_control_start_threshold** with automatically set to 60. 
Am I correct?

**Comment by teackot** [comment]
Yes, they actually modify the same EC parameter just with a 10% offset

**Comment by maniacx** [comment]
Thanks. :+1:

**Comment by teackot** [comment]
Just checked the update out and it works, thanks!
